name: Auto Translate
author: Vedansh (offensive-vk)
description: Automatically Translate a MD File to Other Languages

inputs:
  file:
    description: 'Path of File to Translate'
    required: false
    default: 'README.md'
  github-token:
    description: 'GitHub Token Bearer for Authentication'
    required: true
  committer:
    description: 'Name of the committer'
    required: false
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
  commit-message:
    description: 'Custom commit message'
    required: false
    default: 'Automated Translation Successful ⚡'
  commit-options:
    description: 'Additional commit options (optional)'
    required: false
  language:
    description: 'Language for translation (e.g., es, zh-CN)'
    required: false
    default: 'es'

runs:
  using: 'node22'
  main: 'index.js'

branding:
  icon: book-open
  color: black