name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-translate"
      description: "Github Action to Translate a Markdown Readme to Various Languages."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}