name: CI / Test Action

on:
  push:
    branches: ['master']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: action/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Translate using Action
        uses: ./
        with:
          file: './README.md'
          language: es
          committer: github-actions[bot]
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Translated Markdown File - Readme.md"