name: CI / Test Action

on:
  push:
    branches: ['master']

env:
  github-token: ${{ secrets.BOT_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Translate
        uses: ./
        with:
          github-token: "${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}"
          file: "README.md"
          language: "es"
          committer: "Hamster [bot]"
          commit-message: "CI: Translated Markdown File."