name: CI / Action

on:
  workflow_dispatch:
    inputs:
      branch: 
        type: string
        description: 'The Branch to commit the changes'
        default: 'master'
        required: true
jobs:
  test:
    name: Testing Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: 'es'

      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: 'fr'

      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: 'zh-CN'
          
      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: 'ru'

      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: 'de'

      - name: Commit & Push Changes
        run: |
          git fetch && git pull --verbose
          git config --local user.name "Hamster [bot]"
          git config --local user.email "TheHamsterBot@outlook.com"
          git add .
          git commit -m "📚 Updated Automated Translations


          Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}