name: CI / Action

on:
  workflow_call:
    inputs:
      lang:
        type: string
        description: 'The Language to Translate'
        default: 'es'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        lang: ['es', 'hi', 'fr', 'zh-CN', 'ar', 'de', 'ru']

    name: Test on ${{ matrix.lang }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: ${{ matrix.lang }}

      - name: Commit and Push
        uses: offensive-vk/auto-commit-push@master
        with: 
          branch: ${{ github.ref_name }}
          name: 'TheHamsterBot'
          email: 'TheHamsterBot@outlook.com'
          github-token: ${{ secrets.BOT_TOKEN }}
          message: 'CI: Translated Markdown [${{ matrix.lang }}] File.'