name: CI / Action

on:
  workflow_call:
    inputs:
      lang:
        type: string
        description: 'The Language to Translate'
        default: 'es'
        required: true
  workflow_dispatch:
    inputs:
      lang:
        type: string
        description: 'The Language to Translate'
        default: 'es'
        required: true
      branch: 
        type: string
        description: 'The Branch to commit the changes'
        default: 'master'
        required: true
jobs:
  test:
    strategy:
      matrix:
        lang: ['es', 'hi', 'fr', 'zh-CN', 'ar', 'de', 'ru']

    name: Test on ${{ matrix.lang }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Translate Readme
        uses: ./
        with:
          file: "README.md"
          language: ${{ matrix.lang }}

      - name: Commit & Push Changes
        run: |
          sleep 5
          git fetch && git pull --verbose
          git config --local user.name "Hamster [bot]"
          git config --local user.email "TheHamsterBot@outlook.com"
          git add .
          git commit -m "📚 Updated Automated Translations - ${{ matrix.lang }}


          Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}