name: CI / Test Action

on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
  github-token: ${{ secrets.BOT_TOKEN }}
  repo-token: ${{ secrets.BOT_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Translate
        uses: ./
        with:
          repo-token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
          file: "README.md"
          language: "es"
          committer: "Hamster [bot]"
          commit-message: "CI: Translated Markdown File."